# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: horizoncv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='horizoncv.proto',
  package='acap',
  syntax='proto3',
  serialized_pb=_b('\n\x0fhorizoncv.proto\x12\x04\x61\x63\x61p\"-\n\x0eHorizonMessage\x12\r\n\x05pitch\x18\x01 \x01(\x01\x12\x0c\n\x04\x62\x61nk\x18\x02 \x01(\x01\x42$\n\nacap.modelB\x16HorizonMessageProtocolb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HORIZONMESSAGE = _descriptor.Descriptor(
  name='HorizonMessage',
  full_name='acap.HorizonMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pitch', full_name='acap.HorizonMessage.pitch', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bank', full_name='acap.HorizonMessage.bank', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['HorizonMessage'] = _HORIZONMESSAGE

HorizonMessage = _reflection.GeneratedProtocolMessageType('HorizonMessage', (_message.Message,), dict(
  DESCRIPTOR = _HORIZONMESSAGE,
  __module__ = 'horizoncv_pb2'
  # @@protoc_insertion_point(class_scope:acap.HorizonMessage)
  ))
_sym_db.RegisterMessage(HorizonMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\nacap.modelB\026HorizonMessageProtocol'))
# @@protoc_insertion_point(module_scope)
